### ISSUE TITLE
Problems with the aas-env

### ISSUE THREAD

**Issue by GitHubRudolf** [eclipse-basyx/basyx-applications#264]
**Describe the bug**
I have configured and downloaded the BaSyx Starter Kit. However, when I try to start the containers using docker-compose up -d, I receive an error message regarding the aas-env container. What could be causing this error? I am new to the topic of the Asset Administration Shell and might be missing something.

**Screenshots**
![image](https://github.com/user-attachments/assets/5f8c0cf7-56a1-41e5-8077-e57e0eaee7bd)

Available images in my Docker after the download and pull:
![image](https://github.com/user-attachments/assets/11ba85b5-8889-4c36-b32e-841fb7c96e39)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by FriedJannik** [comment]
Hi @GitHubRudolf,
Thank you for raising the issue.
Could you please share your BaSyx Configuration so we can reproduce the issue?

**Comment by GitHubRudolf** [comment]
Hi @FriedJannik,

Below are the configurations I made in the BaSyx starter kit:
https://www.basyx.org/get-started/introduction

**Application:** Include the AAS Discovery Service.
**Persistence Backend:** Add MongoDB persistence backend.
**MQTT Eventing:** Add MQTT eventing feature.
**Time Series Data:** Don’t include time series data from a linked database (The reason for this is that I am not familiar with the telegraf.conf file).
**AAS Web User Interface:** Add the Web UI.
**Corporate Design:** I added a standard favicon.ico.
**AAS Dashboard:** Add AAS Dashboard.
**AAS Integration:** I uploaded a sample submodel template for a digital nameplate from IDTA.
**Custom Configuration:** No custom configurations were made by me.

Attached you will find the docker-compose.yml, which may be helpful.

[docker-compose Rudolf 03_09_24.zip](https://github.com/user-attachments/files/16844137/docker-compose.Rudolf.03_09_24.zip)

**Comment by FriedJannik** [comment]
@GitHubRudolf thank you for sharing the configuration.
I had no issues starting the Compose File.
As far as I see the only thing that would cause the environment to be unhealthy, would be your Submodel Template, would you mind sharing the logs of the AAS Environment or, even better, your whole basyx-setup.zip generated by the Starter Kit?

**Comment by GitHubRudolf** [comment]
Hi @FriedJannik,
I'd be happy to send you the basyx-setup.zip. I tried running it again on another computer, but I am still getting the same error message.
[basyx-setup.zip](https://github.com/user-attachments/files/16846297/basyx-setup.zip)

**Comment by GitHubRudolf** [comment]
Hi @FriedJannik,

So, you were right; it was indeed the aasx file I was using. As soon as I removed it and used a different example file from examples/BaSyxMinimal/aas, everything worked for the most part. (Sorry, my bad) Is there possibly a guide on how to create a suitable aasx file myself?

I'm actually writing a paper for my university about AAS in a company. Does anyone happen to know any contacts or good sources that I can use for this work?

Thanks in advance!

**Comment by aaronzi** [comment]
Hi @GitHubRudolf,

Creating your own working AAS can sometimes be a bit difficult due to the lack of good open-source tools.
Currently, you have to rely on the [AASX Package Explorer](https://github.com/eclipse-aaspe/package-explorer/releases/tag/v2024-06-10.alpha). Or you could use a commercial tool like the AAS Designer which is part of the [AAS Suite](https://aas-suite.de/) from Metalevel.

As for good literature on AAS, you can find suitable papers at the ETFA ImplAAS Workshop. From there you can use tools like [Connected Papers](https://www.connectedpapers.com/) to find similar articles and papers. I think you will find the information you need there. In addition, the IDTA also provides a [Reading Guide to AAS](https://industrialdigitaltwin.org/wp-content/uploads/2022/12/2022-12-07_IDTA_AAS-Reading-Guide.pdf). I hope this helps.

Best regards,
Aaron
