### ISSUE TITLE
Documentation for Custom Plugin

### ISSUE THREAD

**Issue by mhrimaz** [eclipse-basyx/basyx-applications#30]
Hi,

Where can I find some documentation and further examples about custom plugins? Is it mandatory to write my own plugin with Vue or other frameworks or vanila js would work too?

I would like to also know the limitations of this feature.

Thanks for your help.

**Comment by aaronzi** [comment]
Hi @mhrimaz,

you can find the documentation for the plugin mechanism here: https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Web_UI_/_Features_/_Plugin_Mechanism

I hope this is helpful to you as a starting point. If you have a specific use case and have no idea how to implement a plugin for this, you can also reach out to me via this mail: aaron@zielstorff.com
I am happy to help you.

Regarding your second question, it is possible to write plugins in vanilla js or with a framework of your choice. This link gives you an insight on how to possibly do that: https://chat.openai.com/share/d222b399-ffcb-4377-84ae-f0399107313f
But I would say it is easier to write the plugin in Vue because you don't need to code a wrapper component for your plugin.
