### ISSUE TITLE
AAS UI Error "Submodel Repository URL not set" when using AAS routing

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-applications#37]
I try out the new AAS UI with the provided [example](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples) for AAS v3. When using the [AAS routing feature](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Web_UI_/_Features_/_AAS_Routing) I get in a lot of cases the error message `Submodel Repository URL not set`. When checking the endpoint-settings within the ui it shows that the endpoints for Registry, AAS, Submodel and Concept Description are set. 

I use this URL to test: `http://localhost:3000/?aas=http://localhost:8081/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz`

The same error occurs when adding a path e.g.: `http://localhost:3000/?aas=http://localhost:8081/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz&path=http://localhost:8081/submodels/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9zbS9kZW1vc3VibW9kZWx2Mw`
The only difference is that the "Element Details" of the submodel are displayed but the "AAS Treeview" stays empty

**Comment by aaronzi** [comment]
Hi @mm-mse,

I tried to reproduce that problem but wasn't able to.
Just so we are on the same page. First, I started a clean Docker Compose project with the example [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples).
This is what I'm initially seeing:
![image](https://github.com/eclipse-basyx/basyx-applications/assets/17433117/f5f9fffa-5095-41cf-a8e2-b7d80e6d58ab)
Do the URLs look the same for you?
Next, I copied the first URL you mentioned in your issue:
`http://localhost:3000/?aas=http://localhost:8081/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz`
This is what the UI looks like after pasting the URL in the address bar:
![image](https://github.com/eclipse-basyx/basyx-applications/assets/17433117/916ec856-efc3-4076-8c04-6fd1a62805aa)
Now I tried the second URL with the path query:
`http://localhost:3000/?aas=http://localhost:8081/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz&path=http://localhost:8081/submodels/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9zbS9kZW1vc3VibW9kZWx2Mw`
After I pasted the URL in the address bar I got this:
![image](https://github.com/eclipse-basyx/basyx-applications/assets/17433117/a0136b9a-16f5-4eef-b210-6acb50e6833f)

Just a shot in the blue. Have you checked if your browser's local storage has some old configurations saved for the repository endpoints? The UI in the new version runs on the same port as the old one. I implemented a mechanism where configs are saved in the local storage so that you don't have to reenter the URLs every time you reload the page.

It's also worth checking if you have multiple AAS Environment containers, registry containers or UI containers that could interfere with each other. Please verify the URLs in the UI.

Hope this helps. If not we could also have an online call if needed.
