### ISSUE TITLE
ReferenceElements in Operation can be edited only with numbers in AAS-GUI for AAS-Metamodel-Version 2

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-applications#43]
I add some reference elements into an operation element of the AAS. In the GUI the reference elements can't be entered correctly. I can only type numbers into the field.

![Bild_2023-11-28_132645933](https://github.com/eclipse-basyx/basyx-applications/assets/152281546/2ea29216-50e5-4fb6-ada3-f2a65930368b)

[Test_AAS.json](https://github.com/eclipse-basyx/basyx-applications/files/13487903/Test_AAS.json)

docker-version: eclipsebasyx/aas-gui:v230703
Docker-compose: https://github.com/eclipse-basyx/basyx-java-examples/tree/main/basyx.docker/simple-deployment-with-gui

**Comment by aaronzi** [comment]
Thank you very much for pointing this out. Interesting that you can even see the Operation in the Element Details. I immediately get a JS error. As far as I can evaluate that, the AAS Web UI iterates over the InputVariable**s** array. This is obviously a bug because according to the metamodel it should be _InputVariable_ without the "s" in the end. I suppose this issue is there because the old version of the UI was tested against the BaSyx C# SDK which also has the bug and therefore is the origin of that problem.

The issue is still present in the BaSyx V2 Version of the UI. Unfortunately the BaSyx V1 version of the UI is end of life and therefore won't receive updates. If you still plan to use BaSyx V1 I am afraid you have to manually build the old version of the AAS Web UI and apply the fix for the bug there. This is the problematic line in the code: https://github.com/eclipse-basyx/basyx-applications/blob/c2c589033496651b0eff6c02610547732e34d985/aas-gui/Frontend/aas-web-gui/src/components/SubmodelElements/Operation.vue#L5
