### ISSUE TITLE
Invalid SubmodelElement Entity in GUI for AAS-Metamodel Version 2

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-applications#45]
When I add the Bill of Material Submodel to my AAS and want to display the submodel in the GUI, the GUI says "Invalid SubmodelElement!"

![Bild_2023-11-28_133749866](https://github.com/eclipse-basyx/basyx-applications/assets/152281546/1c86ef22-3a74-4f09-b8a9-c970968fdd91)

[Test_AAS.json](https://github.com/eclipse-basyx/basyx-applications/files/13488034/Test_AAS.json)

docker-image: eclipsebasyx/aas-gui:v230703
docker-compose: https://github.com/eclipse-basyx/basyx-java-examples/tree/main/basyx.docker/simple-deployment-with-gui

**Comment by aaronzi** [comment]
This is the expected behaviour of the AAS Web UI in the Basyx V1 version. The Entity-SubmodelElement wasn't implemented there. The newest version of the UI for BaSyx V2 includes the Entity-Element. For a list of supported SubmodelElements for the old version of the UI, hover over the (i) underneath the **Invalid SubmodelElement** warning.
