### ISSUE TITLE
Submodel URL can not be resolved

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-applications#48]
I create a docker-compose file with an aas-environment, an aas-registry and an aas-gui. I can register an AAS in the gui but when I click on my AAS the failure occur "Submodel URL can not be resolved". I have uploaded my AAS as json-file in the server, as at this time the aasx-file can not be upladed because of problems in serialization.

To reproduce:
- AASX Package Explorer v2023-11-17
- [aas-env-setup.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/13662089/aas-env-setup.zip)

**Comment by FrankSchnicke** [comment]
@aaronzi, I'm not sure if you received a ping due to moving the ticket - thus, here an explicit ping.

**Comment by aaronzi** [comment]
Thank you for pinging me @FrankSchnicke. I was not aware of this issue before. @stolze-ifak, I will take a look into the problem you are encountering and will give you an update later today.

**Comment by aaronzi** [comment]
All right, so looking at your docker-compose.yaml file and your supplied shells, I see several problems. Firstly, why are you configuring the ports including the url/localhost?

Normally this `127.0.0.1:8040:8080` should look like this: `8040:8080`

Also, why are you mapping the environment port to a different port? You can configure it in applications.properties to use the port you want. Then you can just map for example `8041:8041`, which is less prone to errors in the other configurations.

Looking at the configuration of the AAS UI, you commented out the part where the Submodel Repo and ConceptDescription Repo are linked. You would at least need the Submodel Repo to see your AAS content:

`VITE_SUBMODEL_REPO_PATH: "http://localhost:8041/submodels"`.

And the last thing I noticed is that the AAS environment doesn't even start with your provided AAS. There seems to be a problem with the AAS you created in the package explorer. This can happen because the package explorer is not 100% compliant with the metamodel. Therefore, the environment is struggling to read your AAS. I would advise you to check your AAS.

**Comment by stolze-ifak** [comment]
Thanks for your quick answer. 
I solved the problem. But the last thing I didn't understand. In my case I can see both AAS of the setup an both have all implemented submodels.

**Comment by aaronzi** [comment]
That's strange. I probably have an older version of the Docker image for the AAS Environment which has the same tag name as the one you are using. I will download the newest image and test it again. Anyway, I'm happy it works for you now.
