### ISSUE TITLE
Unable to overwrite a submodel-element with new value

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-applications#51]
The AAS with its elements is displayed correctly in the GUI but I can't overwrite the value of a single submodel element. When I want to upload the new value an internal server error occurs. The same error occurs when I add new entries for example in a multilanguage property. 
I tried to change the value in the aas environment via postman and this works.
Thanks for your help.

My Code for reproducing:
[aas-env-setup - Kopie.zip](https://github.com/eclipse-basyx/basyx-applications/files/13901594/aas-env-setup.-.Kopie.zip)

**Comment by aaronzi** [comment]
There is a new version of the AAS Environment and the repositories. I added a feature there for CORS allowed headers. you have to delete and redownload the Docker image of the AAS Environment in order to have this new feature. The version you are currently working with does not support this. Therefore your browser throws CORS related errors (PATCH requests are not allowed out of the box).

[Here](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/examples/aas-env.properties) you can find an example on how to allow all http methods for the AAS Environment.

Regarding MultilanguageProperties, I think the requiered entpoints to add new languages are not yet implemented in BaSyx V2 (BaSyx Java Server SDK). As far as I now this is planned for the near future but I don't now when this will be implemented by Fraunhofer IESE. You could probably ask @FrankSchnicke ragarding those enpoints. Here is the open issue for that feature request: https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/98
