### ISSUE TITLE
Executing operations throws Error status:405 

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-applications#52]
I tried to invoke the _ExampleOperation_ in the _TestAssetAdministrationShell_ (AAS-ID: https://acplt.org/Test_AssetAdministrationShell) of the test_demo_full_example AAS of the [basyx-java-server-sdk/examples](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/aas). 
Therfore I entered one input and one in-/output variable. For simplicity I wrote **Test** for input and **Eins** for in/out.  When I click _Execute_ then the error status 405 occurs.

Thanks for your help.

My Code for reproducing:
[aas-env-setup - Kopie.zip](https://github.com/eclipse-basyx/basyx-applications/files/13901736/aas-env-setup.-.Kopie.zip)

**Comment by aaronzi** [comment]
Hello @stolze-ifak, I'm aware of this issue. There are two main problems: 

First of all I already created a PR for the BaSyx Java Server SDK which adds support for CORS allowed methods. Otherwise  the invoke request wouldn't work. There is already a new version of the AAS Environment on DockerHub, that supports this. You would have to delete the old image  and redownload it to get the newest version.

The second problem is in the UI itself. I haven't updated the Operation SubmodelElement to the new AAS Version (V3). A few changes need to be done here. This will hopefully be done in the next weeks. If you have time constraints regarding this, please let me now.

**Comment by stolze-ifak** [comment]
Hello @aaronzi, I saw the issue in the Basyx Java Server SDK repository after your hint and subscribed it.
We have to present a functioning demonstrator with AAS operations by the end of January. It is therefore a good step to implement this option in both CORS and the UI as soon as possible.

**Comment by aaronzi** [comment]
I will try to publish a release by the end of the week. I can't guarantee anything but right now the progress is looking good.
